package com.chatovich.movie.constant;

/**
 * Contains constants of different parameters and attributes needed for the application
 */
public class Parameters {

    public final static String PASSWORD = "password";
    public final static String PASSWORD_CONFIRM = "confirm_password";
    public final static String CHANGE_LANGUAGE = "change_language";
    public final static String LANGUAGE = "language";
    public final static String ACTORS = "actors";
    public final static String DIRECTORS = "directors";
    public final static String GENRES = "genres";
    public final static String COUNTRIES = "countries";
    public final static String MOVIE_ACTORS = "movieActors";
    public final static String MOVIE_DIRECTORS = "movieDirectors";
    public final static String COMMAND = "command";
    public final static String ID_MOVIE = "id_movie";
    public final static String ID_FEEDBACK = "id_feedback";
    public final static String ID_PARTICIPANT = "id_participant";
    public static final String POSTER_FILE_PATH = "/img/poster";
    public static final String PHOTO_FILE_PATH = "/img/photo";
    public static final String POSTER = "poster";
    public static final String PHOTO = "photo";
    public static final String PARAM_TITLE = "title";
    public static final String EMPTY_FIELDS = "emptyFields";
    public static final String USER_SIGNED_IN = "userSignedIn";
    public static final String LOGIN_FAILED = "loginFailed";
    public static final String LOGIN_EXISTS = "loginExists";
    public static final String REGISTR_FAILED = "registrFailed";
    public static final String SIGNED_USER = "signedUser";
    public static final String INCLUDE_MENU = "includeMenu";
    public static final String NEW_FEEDBACKS = "newFeedbacks";
    public static final String FEEDBACK = "feedback";
    public static final String NO_FEEDBACK = "noFeedback";
    public static final String SHOW_FEEDBACK = "showFeedback";
    public static final String FEEDBACK_ACTION = "feedback_action";
    public static final String FEEDBACK_ADDED = "feedbackAdded";
    public static final String FEEDBACK_ACCEPTED = "feedbackAccepted";
    public static final String FEEDBACK_REJECTED = "feedbackRejected";
    public static final String NEW_PASSWORD = "new_password";
    public static final String USER_UPDATED = "userUpdated";
    public static final String LOGIN = "login";
    public static final String ID_USER = "id";
    public static final String ID_USE = "id_user";
    public static final String USER_RATING = "userRating";
    public static final String MOVIE_MARK = "mark";
    public static final String ANOTHER_USER = "anotherUser";
    public static final String SHOW_ANOTHER_USER = "showAnotherUser";
    public static final String PAGE = "page";
    public static final int MOVIES_PER_PAGE = 3;
    public static final String MOVIES = "movies";
    public static final String MOVIE = "movie";
    public static final String PAGE_QUANTITY = "pageQuantity";
    public static final String CURRENT_PAGE = "currentPage";
    public static final String GENRE = "genre";
    public static final String COUNTRY = "country";
    public static final String PARTICIPANT = "participant";
    public static final String ACTOR = "actor";
    public static final String PARTICIPANTS = "participants";
    public static final String CHOOSE_PARTICIPANT = "chooseParticipant";
    public static final String PARTICIPANT_EXISTS = "participantExists";
    public static final String PARTICIPANT_ADDED = "participantAdded";
    public static final String PARTICIPANT_UPDATED = "participantUpdated";
    public static final String PASSWORDS_NO_MATCH = "passwordsNoMatch";
    public static final String YEAR = "year";
    public static final String BAN = "ban";
    public static final String USERS = "users";
    public static final String USERNAME = "username";
    public static final String CHOOSE_USER = "chooseUser";
    public static final String LIKES = "likes";
    public static final String ACTION = "action";
    public static final String DELETE = "delete";
    public static final String MOVIE_DELETED = "movieDeleted";
    public static final String MOVIE_ADDED = "movieAdded";
    public static final String MOVIE_EXISTS = "movieExists";
    public static final String MOVIE_UPDATED = "movieUpdated";
    public static final String CHOOSE_MOVIE = "chooseMovie";
    public static final String LATEST_FEEDBACKS = "latestFeedbacks";
    public static final String TOP_MOVIES = "topMovies";
    public static final String EMPTY_MOVIES_LIST = "emptyMoviesList";
    public static final String PREVIOUS_PAGE = "prev";
    public static final int BAN_DAYS = 10;
}
